name: Daily Hindalco CSV Update

on:
  workflow_dispatch:  # Manual trigger
  schedule:
      - cron: '0 11 * * *'  # Run at 4:30 PM IST daily

permissions:
  contents: write

jobs:
  update_csvs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install PyPDF2
          
      - name: Check for Existing PDFs
        run: |
          echo "🔍 Checking for existing PDFs in Downloads folder..."
          
          # List all available PDFs
          find Downloads -name "*.pdf" -type f | head -10
          
          # Check if we have recent PDFs
          if find Downloads -name "*.pdf" -type f -mtime -7 | head -1 > /dev/null; then
            echo "✅ Found recent PDF files in Downloads folder"
          else
            echo "⚠️ No recent PDF files found, but continuing with available PDFs"
          fi
          
      - name: Extract CSV from PDF
        run: |
          python csv_from_pdf.py
          
      - name: Commit CSV Updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes in CSV files
          if git diff --quiet csv/ && git diff --staged --quiet csv/; then
            echo "📝 No changes detected in CSV files"
            exit 0
          fi
          
          # Add only CSV files (not PDFs since they're already committed)
          if ls csv/*.csv 1> /dev/null 2>&1; then
            git add csv/
            
            # Commit with informative message
            current_date=$(date '+%Y-%m-%d')
            git commit -m "Daily CSV update for ${current_date} [$(date '+%H:%M:%S')]"
            git push
            
            echo "✅ CSV files updated and committed successfully"
          else
            echo "❌ No CSV files found to commit"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
